### ISSUE TITLE
Add slides and video

### ISSUE THREAD

**Issue by hhkaos** [esridevsummit/arcgis-runtime-building-ios-apps#1]
Hi @nixta are these the resources you used on this one?

https://www.esri.com/content/dam/esrisites/en-us/events/conferences/2021/developer-summit/12270-arcgis-runtime-sdk-for-ios-building-apps.pdf

https://www.youtube.com/watch?v=Xt1JqS7YJZI

**Comment by nixta** [comment]
Hi @hhkaos. Yes. Looks right! You can also find the code here: https://github.com/geeknixta/arcgis-runtime-building-ios-apps
